application: twit-favs
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /assets/(.*\.(gif|png|jpg|js|css))
  static_files: static/assets/\1
  upload: static/assets/(.*\.(gif|png|jpg|js|css))

- url: /ajax/.*
  script: main.py